name: Update Latest Auto Build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ControlBans/**'
      - 'ControlBans-Bungee/**'
      - 'ControlBans-Velocity/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    # THIS IS THE NEW LINE THAT PREVENTS IT FROM RUNNING ON RELEASES
    if: "!contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install

      - name: Generate Commit Info
        id: commit_info
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            COMMIT_COUNT=$(git rev-list --count ${{ github.event.before }}..${{ github.event.after }})
            echo "COMMIT_MESSAGE=How many commits: ${COMMIT_COUNT}" >> $GITHUB_OUTPUT
          else
            echo "COMMIT_MESSAGE=Manually triggered build." >> $GITHUB_OUTPUT
          fi

      - name: Delete Old Release and Tag
        run: |
          gh release delete autobuild-latest --cleanup-tag --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Release and Upload Build Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: autobuild-latest
          name: Latest Auto Build
          prerelease: true
          body: |
            ### ⚠️ Disclaimer
            This is the latest automatic build from the `main` branch. It may contain experimental changes or issues.
            **Use at your own risk.**

            ${{ steps.commit_info.outputs.COMMIT_MESSAGE }}

            For stable versions, please download from [BuiltByBit](https://builtbybit.com/resources/controlbans.78397/) or [Modrinth](https://modrinth.com/plugin/controlbans).
          files: |
            ControlBans/target/*.jar
            ControlBans-Bungee/target/*.jar
            ControlBans-Velocity/target/*.jar
            !**/original-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
