name: Create Auto Build Release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ControlBans/**'
      - 'ControlBans-Bungee/**'
      - 'ControlBans-Velocity/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install

      - name: Generate Build Description
        id: build_description
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            COMMIT_COUNT=$(git rev-list --count ${{ github.event.before }}..${{ github.event.after }})
            echo "RELEASE_BODY=This is an automatic build from the \`main\` branch and includes **${COMMIT_COUNT}** new commit(s)." >> $GITHUB_OUTPUT
          else
            echo "RELEASE_BODY=This is a manually triggered build from the \`main\` branch." >> $GITHUB_OUTPUT
          fi

      - name: Create Release and Upload Build Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: autobuild-${{ github.run_number }}
          name: Auto Build #${{ github.run_number }}
          prerelease: true
          body: |
            ### ⚠️ Disclaimer
            ${{ steps.build_description.outputs.RELEASE_BODY }}
            It may contain experimental changes or issues.
            **Use at your own risk.**

            For stable versions, please download from [BuiltByBit](https://builtbybit.com/resources/controlbans.78397/) or [Modrinth](https://modrinth.com/plugin/controlbans).
          files: |
            ControlBans/target/*.jar
            ControlBans-Bungee/target/*.jar
            ControlBans-Velocity/target/*.jar
            !**/original-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
