name: Create Official Release

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-release:
    name: Build and Create Official Release
    # THIS IS THE NEW LINE THAT MAKES IT RUN ONLY ON RELEASES
    if: "contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install

      - name: Extract Project Version and Commit Count
        id: project_info
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION_TAG=v${VERSION}" >> $GITHUB_OUTPUT
          
          COMMIT_COUNT=$(git rev-list --count HEAD~1..HEAD)
          echo "COMMIT_COUNT=${COMMIT_COUNT}" >> $GITHUB_OUTPUT

      - name: Create New Release and Upload Build Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.project_info.outputs.VERSION_TAG }}
          name: Release ${{ steps.project_info.outputs.VERSION_TAG }}
          prerelease: false
          body: |
            ### Auto Release ðŸŽ‰
            **Release number:** ${{ steps.project_info.outputs.VERSION_TAG }}
            **How many commits and changes:** ${{ steps.project_info.outputs.COMMIT_COUNT }}

            I hope you enjoy the updated version of controlbans.
          files: |
            ControlBans/target/*.jar
            ControlBans-Bungee/target/*.jar
            ControlBans-Velocity/target/*.jar
            !**/original-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
